name: tennis_serve_analysis
description: A App to Analyze a Player's Tennis Serve

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.5
  video_player: ^2.8.1
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.0.15
  image: ^3.0.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/models/
   - assets/lottie/
